[package]
name = "rcc"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
indexmap = "1.9.2"
rcc-macro = { path = "../rcc-macro" }
prettyplease = "0.2"
syn = { version = "2", default-features = false, features = ["full", "parsing"] }
