[package]
name = "rcc"
version = "0.0.1"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
seq-macro = "0.3.2"
rayon = "1.6"
ark-ff = "0.4.0"
ark-bn254 = "0.4.0"
rust-format = "0.3.4"
fixedstr = "0.2.9"
indexmap = "1.9.2"
rcc-macro = { path = "rcc-macro" }

[profile.dev]
opt-level = 1
