[package]
name = "rcc"
version = "0.0.1"
edition = "2021"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
rayon = "1.6"
ark-ff = "0.4.0"
ark-bn254 = "0.4.0"
rust-format = "0.3.4"
indexmap = "1.9.2"
rcc-macro = { path = "rcc-macro" }
