[package]
name = "rcc-mockcomposer"
version = "0.0.1"
edition = "2021"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
ark-ff = "0.4.0"
ark-bn254 = "0.4.0"
indexmap = "1.9.2"
rcc = { path = "../rcc" }
rcc-macro = { path = "../rcc-macro" }
