[package]
name = "rcc-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"

[[bin]]
name = "main"
path = "src/main.rs"
